README.md, contributing.md
created contributing.md file
Fixes #6 
---
=> created contributing.md file

README.md
=> Program Section Added #24

README.md
please review my PR @Aaishpra  
fixes #38
and let me know if any further changes required .  :)
thanks
=> added admin section --issue38

Woodog/templates/dashboard/dashboard.html, Woodog/templates/partials/base.html, Woodog/templates/woodogdata/index.html
I've fixed some issues on the home page
---
=> Fix Home Page Issues

Woodog/templates/partials/base.html, Woodog/templates/partials/base_auth.html
I changed the footer copyright year.
It will automatically update itself.
Issue Number: #60 
Fixes #
---
=> Changed Copyright Footer Year Using JS

Woodog/templates/woodogdata/about.html
Fixes: #48 
Hey @Aaishpra @khushishikhu 
I have added the about us page.
Please check and update me if any changes need to be made.
Thanks
Fixes #
---
=> Added About Us Page

Woodog/templates/woodogdata/contact.html
Fixes: #68 
Hey @hariramjp777 @khushishikhu 
Added the contact us page.
Please check and update.
Thanks
Fixes #
---
=> Added Contact Us Page

Woodog/authentication/urls.py, Woodog/authentication/views.py, Woodog/templates/authentication/set-newpassword.html
Created Change Password page
Fixes #97 
---
=> Created Change Password page

Woodog/Woodog/static/js/bootstrap-auto-dismiss-alert.js, Woodog/templates/partials/_messages.html, Woodog/templates/partials/base.html, Woodog/templates/woodogdata/index.html
enhanced alert messages
Fixes #99 
https://www.awesomescreenshot.com/video/4276470?key=205b131b13bca28e345923f2f02fdc3d
---
=> enhanced alert messages

Woodog/templates/partials/base_auth.html, Woodog/templates/partials/header.html
I have made customer scroll bar button
Fixes #104 
https://user-images.githubusercontent.com/69043944/123955424-0e951c00-d956-11eb-9371-5ac4c1c61854.mp4
=> custom scrollbar

Woodog/templates/authentication/login.html, Woodog/templates/authentication/register.html, Woodog/templates/partials/_messages.html, Woodog/templates/partials/footer.html, Woodog/templates/partials/header.html, Woodog/templates/woodogdata/about.html, Woodog/templates/woodogdata/contact.html, Woodog/templates/woodogdata/index.html
Made webpages responsive
Fixes #101 
https://www.awesomescreenshot.com/video/4314863?key=a69bf287c97f5f4cb104476e5ed4a336
---
=> Made webpages responsive

Woodog/templates/partials/base.html, Woodog/templates/partials/footer.html, Woodog/templates/partials/header.html, Woodog/woodogdata/urls.py, Woodog/woodogdata/views.py
Added gallery page
Fixes #49 
https://www.awesomescreenshot.com/video/4330496?key=d5119727956ab2aeee5bef457f06ff16
---
=> Added gallery page

Woodog/templates/partials/header.html
Made responsive navbar
Fixes #37 
https://www.awesomescreenshot.com/video/4343859?key=496e13a71eb00a55212a5afb518cd48b
---
=> Made responsive navbar

README.md
I have added levels at README.md file
Fixes #120
=> adding levels in readme.md file

Woodog/authentication/urls.py, Woodog/authentication/views.py, Woodog/templates/authentication/forget_password.html
I have created forget password page
Fixes #107
=> forget password page

Woodog/templates/woodogdata/FAQ.html
Enhanced and made FAQ page responsive
- Changed the background,button and text color according to UI
-  Made the page responsive
-  Fixed the overflowing content in mobile view
Fixes #125 
https://www.awesomescreenshot.com/video/4385520?key=d4dd3577279b032d469f5ab9b5188973
---
=> Enhanced and made FAQ page responsive

Woodog/templates/partials/base.html
Added chatbot
Fixes #129 
https://www.awesomescreenshot.com/video/4434690?key=9e0ff4930db099e31dd4a7e1a359f7c0
---
=> Added chatbot

Woodog/Woodog/settings.py, Woodog/authentication/urls.py, Woodog/authentication/views.py, Woodog/templates/authentication/forget_password.html, Woodog/templates/authentication/login.html, Woodog/templates/authentication/reset-password.html
Added forgot password functionality
Fixes #123 
https://www.awesomescreenshot.com/video/4400193?key=24bbab30cdd1959fa960853f5687c23a
---
=> Added forgot password functionality

Woodog/templates/partials/footer.html, Woodog/templates/partials/header.html
=> Added Dropdown in Navbar

Woodog/templates/woodogdata/about.html, Woodog/templates/woodogdata/contact.html, Woodog/templates/woodogdata/service.html
Fixes #137 
https://www.awesomescreenshot.com/video/4446760?key=7313aab352dd6f9836fd488e0037dcfe
---
=> fixed service page

Woodog/templates/authentication/register.html
=> register page updated
